
Gem::Specification.new do |s|
  s.name        = 'simpleiban'
  s.version     = '0.0.1'
  s.date        = '2015-05-05'
  s.summary     = "IBAN account verification"
  s.description = "Simple IBAN account checking - verifies that IBAN is valid"
  s.authors     = ["Inigo Gonzalez"]
  s.email       = 'igponce at gmail dot com'
  s.files       = ["lib/simpleiban.rb"]
  s.homepage    = 'http://rubygems.org/gems/simpleiban'
  s.license       = 'MIT'
end
